export enum SessionStatus {
  IDLE = "IDLE",
  ACTIVE = "ACTIVE",
  PAUSED = "PAUSED",
  ENDED = "ENDED",
}

export enum EventType {
  SESSION_CREATED = "SESSION_CREATED",
  SESSION_STARTED = "SESSION_STARTED",
  SESSION_PAUSED = "SESSION_PAUSED",
  SESSION_RESUMED = "SESSION_RESUMED",
  SESSION_ENDED = "SESSION_ENDED",
  TRANSACTION_CREATED = "TRANSACTION_CREATED",
  WRISTBAND_SCANNED = "WRISTBAND_SCANNED",
}
